### ISSUE TITLE
not able to update the port

### ISSUE THREAD

**Issue by akshay27395** [alexnzarov/pm2-web-ui#18]

**Comment by alexnzarov** [comment]
There is no way in Next.js to set a port via an environment variable or some configuration option.

But you can change the package.json file, like this:
```js
"scripts": {
  "dev": "next dev -p 3000",
  "build": "next build",
  "start": "next start -p 80"
}
```

**Comment by akshay27395** [comment]
It works!!! Thank you so much.

**Comment by akshay27395** [comment]
> There is no way in Next.js to set a port via an environment variable or some configuration option.
> 
> But you can change the package.json file, like this:
> 
> ```js
> "scripts": {
>   "dev": "next dev -p 3000",
>   "build": "next build",
>   "start": "next start -p 80"
> }
> ```

It works!!! Thank you so much.
