### ISSUE TITLE
make daemon

### ISSUE THREAD

**Issue by alexnzarov** [alexnzarov/pm2-web-ui#2]
Add ability to connect to daemons that interact with pm2 instances from different machines.

**Comment by ashinga48** [comment]
is this happening soon?

**Comment by Tam2** [comment]
I would also be interested in this, the ability to monitor pm2 instances across different machines

**Comment by ashinga48** [comment]
I used this package https://github.com/ashinga48/pm2-server-monitor-single, and customised but this uses socket server and reports only one single container processes,

Is there any lead on how to build get different machines info, I could add this feature in this. @Tam2 @alexnzarov
