### ISSUE TITLE
Administration routes not found

### ISSUE THREAD

**Issue by AlexVanSteenhoven** [alexnzarov/pm2-web-ui#22]
When i want to add a new user or deploy an new application I will get a 404.
Is this an known issue, or is it simply not implemented yet.

> http://myip:3000/users
![image](https://user-images.githubusercontent.com/67007082/139869933-9ade1908-1502-41df-ab08-164aa04f983b.png)

> http://myip:3000/deploy
![image](https://user-images.githubusercontent.com/67007082/139869717-1417a867-d631-498a-855d-48226e3fe690.png)

**Comment by iamprageeth** [comment]
@AlexVanSteenhoven  Did u find the solution for this?

**Comment by gabmunoz** [comment]
Did u find the solution for this?
